#!/usr/bin/env python3

import sys, os, re ,json , subprocess, requests
from subprocess import check_output, run

result = run(
        ["git", "rev-parse", "HEAD"],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False
    )

if result.stdout.decode("utf-8") == "HEAD":
    file_to_commit = check_output([ 'git', 'diff', '--cached', '--name-status' , 'HEAD'])
else:
    file_to_commit = check_output([ 'git', 'diff', '--cached', '--name-status'])
file_to_commit = file_to_commit.decode("utf-8")
file_to_commit = file_to_commit.replace("M\t", " ")
file_to_commit = file_to_commit.replace("C\t", " ")
file_to_commit = file_to_commit.replace("R\t", " ")
file_to_commit = file_to_commit.replace("A\t", " ")
file_to_commit = file_to_commit.replace("U\t", " ")
file_to_commit = file_to_commit.strip()
file_to_commit = file_to_commit.split(" ")

for i in file_to_commit:
    if "D\t" in i.strip():
        continue
    if "package.json" in i.strip():
        if os.stat(i.strip()).st_size == 0:
            print("WARNING:\tYour file {} is empty. You may want to check that you did not make a mistake".format(i.strip()))
        else:
            f = open(i.strip(),)
            try:
                data = json.load(f)
                if "dependencies" in data:
                    package_list = list(data["dependencies"].keys())
                    print("Scanning your dependencies. Please hold on tight")
                    r = requests.post('http://127.0.0.1:5000/threat/search',json={"package_manager_type" : "npm","package_list" : package_list,"level": 0})
                    if r.status_code == 200:
                        r_content = r.json()
                        for h in r_content:
                            if len(r_content[h]) != 0:
                                print("The package {} in your dependencies is vulnerable. Please visit our website at http://www.google.com for more information".format(h))
                if "devDependencies" in data:
                    package_list = list(data["devDependencies"].keys())
                    print("Scanning your devdependencies. Please hold on tight")
                    r = requests.post('http://127.0.0.1:5000/threat/search',json={"package_manager_type" : "npm","package_list" : package_list,"level": 0})
                    if r.status_code == 200:
                        r_content = r.json()
                        for h in r_content:
                            if len(r_content[h]) != 0:
                                print("The package {} in your dependencies is vulnerable. Please visit our website at http://www.google.com for more information".format(h))
                f.close()
            except:
                print("WARNING:\tYour file {} is not readable as a json file. Please check that you did not make a mistake".format(i.strip()))
                f.close()
                exit(1)

exit(1)